### ISSUE TITLE
Timezone in documentation

### ISSUE THREAD

**Issue by GB127** [racetimeGG/racetime-app#165]
So I'm working on a code to fetch current races and compare to a specific date. And it seems that the races I'm comparing to are opened in the future:

![image](https://user-images.githubusercontent.com/62620901/157732331-1ff9896f-102b-4972-bde8-24c70630a790.png)

![image](https://user-images.githubusercontent.com/62620901/157732249-e055bffd-9b2b-46a4-bf66-1889b543031b.png)

The only logical explanation I can find is that the timezone is different. And it's not specified on the documentation. From my quick research, only the format of the data is specified. Would be neat to have the timezone as well.

**Comment by deains** [comment]
Hi @GB127, the timezone for all date/time values are UTC. The `Z` suffix at the end of a ISO 8601 date indicates the UTC time zone as per the standard.

**Comment by GB127** [comment]
Woah I did not know that. Thank you for the quick answer!
