### ISSUE TITLE
Delete chat messages

### ISSUE THREAD

**Issue by deains** [racetimeGG/racetime-app#17]
Allow moderators to purge messages in race chat.

**Comment by Killklli** [comment]
Hey in regards to this, do you think when a message is purged we remove it from the /log? or do we just remove it from the display at the time and treat it as normal in the log file. I think we do the latter, but before I go start doing work on it I'd like to know what route you would prefer.

**Comment by deains** [comment]
The chat log should only include the deleted message if downloaded by a moderator. There should probably be an indicator in the log as well that the message was deleted (maybe including who by)
