### ISSUE TITLE
Feature Request - Public API - Allow Querying More than 10 Races per Page

### ISSUE THREAD

**Issue by YourAverageLink** [racetimeGG/racetime-app#212]
I recently created [a data visualizer](https://github.com/YourAverageLink/racetime-data) for visualizing head-to-head matchups on RaceTime. Would it be possible to allow API calls to fetch more than 10 races per page? I currently have to asynchronously fetch each page of race data for a slug and update the table live as they come in, so it would be nice to cut down on loading times by fetching race data in bulk.

**Comment by deains** [comment]
I can add something in to increase the default limit, but your app ought to cache races that have already been fetched once. After recording none of the data is likely to change, so fetching them all again is just wasteful really.

**Comment by YourAverageLink** [comment]
That's fair, I do plan on caching fetched results. This was more to see if it was possible to cut down on the initial load time when a user inputs a slug for the first time.

**Comment by deains** [comment]
I've added the ability to specify `per_page` up to 100: https://github.com/racetimeGG/racetime-app/wiki/Public-API-endpoints#past-category-races
