### ISSUE TITLE
Expose race info field in all races and category endpoint.

### ISSUE THREAD

**Issue by Andols0** [racetimeGG/racetime-app#41]
Hi there!

Exposing the info field from the Race detail endpoint
`info: String containing additional information for race entrants, as set by the monitors.`
to the all races and category endpoint would help with identifying different races.
At the moment you have to do a race detail request for every race to be able to identify the difference between multiple races with the same goal.

**Comment by deains** [comment]
@Andols0 I've added this in, hope you don't mind the wait. It should go into production tomorrow morning.
