### ISSUE TITLE
Allow bots to start races

### ISSUE THREAD

**Issue by deains** [racetimeGG/racetime-app#42]
Give bots the ability to create a race room, send invites to specific users, set race monitors, and enforce a particular start time.

**Comment by deains** [comment]
Most of this done, but starting races still needs an endpoint. Updated summary for clarity.

**Comment by tcprescott** [comment]
I do have a workaround for this, for now, so my use case isn't as pressing.

**Comment by deains** [comment]
Done in 1529922
