### ISSUE TITLE
New Endpoint for complete race data of a category

### ISSUE THREAD

**Issue by scaramangado** [racetimeGG/racetime-app#51]
Add an endpoint `/<category>/races/data` to allow querying a (paginated) list of all open and finished races of a category.

**Usecases:**
- Query all races of a player to calculated average times etc.
- Automatically check for races awaiting recording
- Alternate mode of the race announcer bot showing the race status as "awaiting recording" / "recorded" instead of deleting finished races

**Comment by deains** [comment]
I've not added documenation for this yet, but you'll find the endpoint here: https://racetime.gg/oot/races/data

Races are sorted by `ended_at`, most recent first. Add `?page=X` to the URL to get subsequent pages of data, i.e. https://racetime.gg/oot/races/data?page=2 https://racetime.gg/oot/races/data?page=3 and so on.
