### ISSUE TITLE
Active vs. open races

### ISSUE THREAD

**Issue by GB127** [racetimeGG/racetime-app#76]
Hello,

when I go to racetime.gg,

I see multiples games having "active races". It seems that actives consider "open races" and "on-going races" to be the same.

This is a little annoyance when you want to know what games has races that are currently open to join.

I'd love to see a distinction somewhere.

**Comment by deains** [comment]
Def a good idea, and easy to implement. My favourite combo. 😁

**Comment by GB127** [comment]
Thank you very much! Already better. :)
