### ISSUE TITLE
Add an option to disable auto start for races

### ISSUE THREAD

**Issue by wooferzfg** [racetimeGG/racetime-app#88]
Races will currently always start when all the runners in the race are ready. For races where a race must be started by a bot, a gatekeeper must be used to prevent the race from starting too early.

It would be convenient to have an option to disable races auto starting, which would require the race to begin with a force start. This would bypass the need for a gatekeeper in these types of situations.

**Comment by deains** [comment]
Added in a6237ff 🎉
